% Copyright 2012 Joseph Moster

%% Basics
%parseST and the other functions detailed here get a filename as an
%argument.  The file should contain the data dumped by AVL using the
%ST menu.
myST = parseST('./sampleData/plane1690.st')

%Access any data field like this:
myST.CLa

%Control surface information is availabe in the surface section
surfName = myST.surface(1).name;
fprintf(1,'The name of the control surface is "%s"\n', surfName);

%parseSB similar to parseST but for SB files
mySB = parseSB('./sampleData/plane2243.sb')

%Access any data field like this:
mySB.CXu

%The parseRunCaseHeader and parse Config functions work on ST, SB, and other AVL
%generated files
runCaseST = parseRunCaseHeader('./sampleData/plane1690.st')
myConfigST = parseConfig('./sampleData/plane1690.st')

fprintf(1,'This aircraft was analyzed at an alpha of %f \n', runCaseST.alpha);

runCaseSB = parseRunCaseHeader('./sampleData/plane2243.sb');
myConfigSB = parseConfig('./sampleData/plane2243.sb');

fprintf(1,'This next aircraft was analyzed at an alpha of %f \n', runCaseSB.alpha);
fprintf(1,'It has a S reference area of %f \n', myConfigSB.Sref);

%parseRunCaseFile
%loads all run-case data from a run-case file
runCases = parseRunCaseFile('./sampleData/rc43.run');
runCases
fprintf(1,'The first run-case is "%s" \n', runCases(1).name);

%% Intermediate
% The parseSF function loads data from a strip forces output file "SF"
% output.  This can be used to determine local cl values along a surface.
% This can be used for determining if a wing is stalled by comparing the cl
% values along the wind to the viscous solution of max cl as generated by
% xfoil or from wind tunnel data.

%The first argument is the filename of the file to be parsed.
%The second argument is the name of the surface to be loaded.  In this case
%the function will load the 'Wind-Right' surface.  If you open the
%'./plane9001.sf' file in a text editor you will see that other valid
%surfaces include 'Rudder' and 'Elevator-Right'.  These names are those
%that you gave the surfaces when you created the AVL model, so you should
%know them or at least look them up before using this function.

mySurfaces = parseSF('./sampleData/plane9001.sf');

%Easily get the index of a particular surface whose name we know
sIndex = getSurfaceByName(mySurfaces,'Wing-Right');

%Get the strip forces for the surface
myStripForces = mySurfaces(sIndex).strip;

%You can then access a particular strip as shown below
myStripForces{1}

%Example code for detecting stall
%Try changing the max CL to 1.7 for an unstalled wing

CLMax = 1.4;
stalled = 'not stalled';
for i=1:length(myStripForces)
    if(myStripForces{i}.cl>CLMax)
        stalled = 'stalled';
    end
end
fprintf(1,'The wing is %s \n',stalled);





