 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: SpiffySparrow                                               
     # Surfaces =   3
     # Strips   =  50
     # Vortices = 600

  Sref = 0.32520       Cref = 0.22860       Bref =  1.4224    
  Xref = 0.50000E-01   Yref =  0.0000       Zref = 0.50000E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.68987     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =  -0.05233     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.03945
  CZtot =  -0.37427     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.37565
  CDtot =   0.04127
  CDvis =   0.03200     CDind =   0.00927
  CLff  =   0.37537     CDff  =   0.00926    | Trefftz
  CYff  =   0.00000         e =    0.7785    | Plane  

   ElevatorCS      =   1.230000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.818624    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.155920
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.025428
 y  mom.  Cm |    Cma =  -1.434971    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.060413

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000003    CLq =   9.841484    CLr =   0.000000
 y  force CY |    CYp =   0.048701    CYq =   0.000000    CYr =   0.140731
 x' mom.  Cl'|    Clp =  -0.480505    Clq =   0.000000    Clr =   0.118673
 y  mom.  Cm |    Cmp =  -0.000001    Cmq = -15.253433    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.026840    Cnq =   0.000000    Cnr =  -0.073394

                  ElevatorCS   d1 
                  ----------------
 z' force CL |   CLd1 =   0.007429
 y  force CY |   CYd1 =   0.000000
 x' mom.  Cl'|   Cld1 =   0.000000
 y  mom.  Cm |   Cmd1 =  -0.024451
 z' mom.  Cn'|   Cnd1 =   0.000000
 Trefftz drag| CDffd1 =  -0.000179
 span eff.   |    ed1 =   0.045796



 Neutral point  Xnp =   0.118076

 Clb Cnr / Clr Cnb  =   0.260313    (  > 1 if spirally stable )
