 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Design6.0                                                   
     # Surfaces =   7
     # Strips   = 140
     # Vortices =1584

  Sref =  3.0569       Cref = 0.68235       Bref =  4.5000    
  Xref =  1.3700       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.17200     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =  -0.07017     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.06190
  CZtot =  -0.14516     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.14106
  CDtot =   0.07809
  CDvis =   0.07600     CDind =   0.00209
  CLff  =   0.14111     CDff  =   0.00205    | Trefftz
  CYff  =   0.00000         e =    0.4665    | Plane  

   elevator        =   0.00000
   aileron         =   0.00000
   flap            =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.966331    CLb =   0.000002
 y  force CY |    CYa =  -0.000001    CYb =  -0.385092
 x' mom.  Cl'|    Cla =  -0.000008    Clb =  -0.078750
 y  mom.  Cm |    Cma =  -0.517414    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.167264

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000022    CLq =   9.792579    CLr =  -0.000001
 y  force CY |    CYp =  -0.072388    CYq =  -0.000010    CYr =   0.397432
 x' mom.  Cl'|    Clp =  -0.470978    Clq =  -0.000007    Clr =   0.053415
 y  mom.  Cm |    Cmp =   0.000002    Cmq = -24.234623    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.016408    Cnq =   0.000003    Cnr =  -0.225034

                  elevator     d1     aileron      d2     flap         d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.003858   CLd2 =   0.000000   CLd3 =   0.016438   CLd4 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.001263   CYd3 =   0.000000   CYd4 =   0.004661
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =  -0.008286   Cld3 =   0.000000   Cld4 =   0.000371
 y  mom.  Cm |   Cmd1 =  -0.015578   Cmd2 =   0.000000   Cmd3 =  -0.004078   Cmd4 =   0.000000
 z' mom.  Cn'|   Cnd1 =   0.000000   Cnd2 =  -0.000726   Cnd3 =   0.000000   Cnd4 =  -0.002789
 Trefftz drag| CDffd1 =   0.000195 CDffd2 =   0.000000 CDffd3 =   0.000156 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.018773    ed2 =   0.000000    ed3 =   0.073314    ed4 =   0.000000



 Neutral point  Xnp =   1.441091

 Clb Cnr / Clr Cnb  =   1.983517    (  > 1 if spirally stable )
